version: 2.1

orbs:
  node: circleci/node@4.0.0

executors:
  tools-deps:
    docker:
      - image: circleci/clojure:tools-deps
    working_directory: ~/repo

  lein:
    docker:
      - image: circleci/clojure:lein-2.9.1
    working_directory: ~/repo

jobs:
  todomvc_test:
    executor: tools-deps
    working_directory: ~/repo/examples/todomvc
    steps:
      - checkout:
          path: ~/repo
      - node/install
      - run: npm install
      - run: npm run compile-test
      - run: node out/test.js

  rehook_dom_test:
    executor: lein
    working_directory: ~/repo/rehook-dom
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: rehook-dom-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: rehook-dom-{{ checksum "project.clj" }}
      - run: lein test

workflows:
  version: 2.1
  general_build:
    jobs:
      - todomvc_test
      - rehook_dom_test
